# Generated by Django 5.2.6 on 2025-09-20 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('resumen_creado', 'Resumen Creado'), ('esquema_creado', 'Esquema Creado'), ('flashcard_creada', 'Flashcard Creada'), ('cuestionario_creado', 'Cuestionario Creado'), ('cuestionario_completado', 'Cuestionario Completado'), ('flashcard_practicada', 'Flashcard Practicada')], max_length=30)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('objeto_id', models.IntegerField(blank=True, null=True)),
                ('app_origen', models.CharField(max_length=20)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Actividad del Historial',
                'verbose_name_plural': 'Actividades del Historial',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
