# Generated by Django 5.2.6 on 2025-09-20 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadhistorial',
            name='tipo',
            field=models.CharField(choices=[('resumen_creado', 'Resumen Creado'), ('esquema_generado', 'Esquema Generado'), ('flashcards_creadas', 'Flashcards Creadas'), ('flashcards_practicadas', 'Flashcards Practicadas'), ('cuestionario_creado', 'Cuestionario Creado'), ('cuestionario_completado', 'Cuestionario Completado')], max_length=30),
        ),
    ]
