# Generated by Django 5.2.4 on 2025-09-20 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('historial', '0002_alter_actividadhistorial_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadhistorial',
            name='objeto_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
