# Generated by Django 5.2.6 on 2025-09-15 03:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('contenido_original', models.TextField()),
                ('num_preguntas', models.IntegerField(default=10)),
                ('dificultad', models.CharField(choices=[('facil', 'Fácil'), ('medio', 'Medio'), ('dificil', 'Difícil')], default='medio', max_length=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('completado', models.BooleanField(default=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('texto', models.TextField()),
                ('opciones', models.JSONField()),
                ('respuesta_correcta', models.IntegerField()),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='cuestionarios.cuestionario')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='ResultadoCuestionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntuacion', models.FloatField()),
                ('respuestas_correctas', models.IntegerField()),
                ('respuestas_incorrectas', models.IntegerField()),
                ('total_preguntas', models.IntegerField()),
                ('tiempo_completado', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado', to='cuestionarios.cuestionario')),
            ],
        ),
        migrations.CreateModel(
            name='RespuestaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta_seleccionada', models.IntegerField(blank=True, null=True)),
                ('es_correcta', models.BooleanField(default=False)),
                ('fecha_respuesta', models.DateTimeField(auto_now_add=True)),
                ('cuestionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.cuestionario')),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cuestionarios.pregunta')),
            ],
            options={
                'unique_together': {('cuestionario', 'pregunta')},
            },
        ),
    ]
