# Generated by Django 5.2.6 on 2025-09-16 21:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Esquema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('jerarquico', 'Esquema Jerárquico'), ('conceptual', 'Mapa Conceptual'), ('cronologico', 'Línea de Tiempo')], default='jerarquico', max_length=20)),
                ('fuente', models.CharField(choices=[('archivo', 'Archivo'), ('texto', 'Texto')], max_length=20)),
                ('contenido_original', models.TextField()),
                ('contenido_procesado', models.JSONField()),
                ('archivo_original', models.FileField(blank=True, null=True, upload_to='esquemas/archivos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='ConceptoMapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=200)),
                ('es_central', models.BooleanField(default=False)),
                ('descripcion', models.TextField(blank=True)),
                ('posicion_x', models.IntegerField(default=0)),
                ('posicion_y', models.IntegerField(default=0)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='esquemas.esquema')),
            ],
        ),
        migrations.CreateModel(
            name='EventoTimeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('orden', models.IntegerField(default=0)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='esquemas.esquema')),
            ],
            options={
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='NodoEsquema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('nivel', models.IntegerField(default=1)),
                ('orden', models.IntegerField(default=0)),
                ('esquema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodos', to='esquemas.esquema')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='esquemas.nodoesquema')),
            ],
            options={
                'ordering': ['nivel', 'orden'],
            },
        ),
    ]
