# Generated by Django 5.2.6 on 2025-09-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('esquemas', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conceptomapa',
            options={'verbose_name': 'Concepto de Mapa', 'verbose_name_plural': 'Conceptos de Mapa'},
        ),
        migrations.AlterModelOptions(
            name='esquema',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Esquema', 'verbose_name_plural': 'Esquemas'},
        ),
        migrations.AlterModelOptions(
            name='eventotimeline',
            options={'ordering': ['orden'], 'verbose_name': 'Evento de Timeline', 'verbose_name_plural': 'Eventos de Timeline'},
        ),
        migrations.AlterModelOptions(
            name='nodoesquema',
            options={'ordering': ['nivel', 'orden'], 'verbose_name': 'Nodo de Esquema', 'verbose_name_plural': 'Nodos de Esquema'},
        ),
        migrations.AddField(
            model_name='conceptomapa',
            name='conexiones',
            field=models.JSONField(blank=True, default=list, help_text='Lista de conceptos relacionados'),
        ),
        migrations.AddField(
            model_name='conceptomapa',
            name='ejemplos',
            field=models.JSONField(blank=True, default=list, help_text='Ejemplos del concepto'),
        ),
        migrations.AddField(
            model_name='conceptomapa',
            name='importancia',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='consecuencias',
            field=models.JSONField(blank=True, default=list, help_text='Lista de consecuencias'),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='contexto',
            field=models.TextField(blank=True, help_text='Contexto histórico o situacional'),
        ),
        migrations.AddField(
            model_name='eventotimeline',
            name='importancia',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='nodoesquema',
            name='detalles',
            field=models.TextField(blank=True, help_text='Información adicional expandible'),
        ),
        migrations.AddField(
            model_name='nodoesquema',
            name='importancia',
            field=models.CharField(choices=[('alta', 'Alta'), ('media', 'Media'), ('baja', 'Baja')], default='media', max_length=10),
        ),
        migrations.AddField(
            model_name='nodoesquema',
            name='palabras_clave',
            field=models.JSONField(blank=True, default=list, help_text='Lista de palabras clave'),
        ),
    ]
