# Generated by Django 5.2.4 on 2025-09-13 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0001_initial'),
    ]

    operations = [
    ]
