# Generated by Django 5.2.4 on 2025-09-20 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumenes', '0002_auto_20250912_2253'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='summary',
            options={'ordering': ['-created_at'], 'verbose_name': 'Resumen', 'verbose_name_plural': 'Resúmenes'},
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('txt', 'Texto'), ('pdf', 'PDF'), ('doc', 'Word'), ('docx', 'Word'), ('manual', 'Texto Manual')], max_length=10),
        ),
    ]
